sudo: required
services:
  - docker

before_install:
  - sudo docker build -t bui1der/react-test -f ./client/Dockerfile.dev ./client

script:
  - sudo docker run -e CI=true bui1der/react-test npm test

after_success:
  - sudo docker build bui1der/multi-client ./client
  - sudo docker build bui1der/multi-nginx ./nginx
  - sudo docker build bui1der/multi-server ./server
  - sudo docker build bui1der/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  #Take those images and push them to docker hub
  - sudo docker push bui1der/multi-client
  - sudo docker push bui1der/multi-nginx
  - sudo docker push bui1der/multi-server
  - sudo docker push bui1der/multi-worker

language: generic 

